public with sharing class BaselineCondition_OSP_CRF {
  
  public String CRFId;
  public String DiagnosisType;
  public String OtherDaignosis;
  public String Daignosis;  
  public String SeverityGrade;
  public String Attribution;
  public String OnsetMonth;
  public String OnsetDay;
  public String OnsetYear;
  public String Resolved;
  public String EndMonth;
  public String EndDay;
  public String EndYear;
 }