public with sharing class BloodSpecimenCRF {
	public String PatientId;
	public String CRFId;
	public String CollectionDate;
	public String TimePoint;
	public String NoOfSampleCollected_Serum;
	public String NoOfSampleCollected_Plasma;
	public String NoOfSampleCollected_buffyCoat;
	public String ReasonallSamplenotCollected;
	public String Other;
	public String PatientConsentedForThisStudy;
	public String PatientConsentedForOutSideStudy;
	public String Status;
	public String CompletedDate;
}