public with sharing class ChemoSummaryCRF {
  public String PatientId;
  public String CRFId;
  public String FirstDateofTaxaneTherapy;
  public String LastDateofTaxaneTherapy;
  public String TaxaneRegimenTreatmentEndReasons;
  public String OtherReason;
  public String FirstDateofAnthracyclineTherapy;
  public String LastDateofAnthracyclineTherapy;
  public String AnthracyclineRegimenTreatmentEndReason; 
  public String OtherReason1;
  public String FirstDateofInvestigationalTherapy;
  public String LastDateofInvestigationalTherapy;
  public String InvestigationalRegimenTreatmentEndReason;
  public String OtherReason2;
  public String CompletedDate;
  public String Status;
}