public with sharing class DCIS_OSP_CRF {
  
  public String CRFId;
  public String PunctateNecrosis;
  public String Comedonecrosis;
  public String Papillary;
  public String Micropapillary;
  public String Necrosis;
  public String Cribiform;
  public String Cruciform;
  public String Clinging;
  public String Solid;
  public String Apocrine;
  public String IntraCysticEncystedPapillary;
  public String Other;
  public String Otherifothermentiontypeintextbox;
  public String Calcifications;
  public String CalcificationsPresent;
  public String NuclearGrade;
  public String DCIS;
  public String UnknownNotReported;
  public String TotalHistologicalSpan;
  public String TotalHistologicalSpanMeasurementUnit;
  public String Margin;
  public String ClosestMargin;
  public String SpecificClosestMargin;
  public String SpecificClosestMarginMeasurementUnit;
}