public with sharing class LosttoFollowupCRF {
  public String PatientId;
  public String Lastcontactbefore2yrs;
  public String Dateoflastcontact;
  public String SocialSecDeathIndexResearch;
  public String SocialSecDeathIndexResearchDate;
  public String Sendcertifiedregisteredltrtoknown;
  public String SendcertifiedregisteredltrDATE;
  public String SendcertifiedregisteredltrResponse;
  public String CompletedDate;
  public String Status;
}