public with sharing class MenopausalStatus {
	public String PatientId;
	public String DateOfLastMenstrualPeriod;
	public String UnknownDate;
	public String UnknownDate12MonthsAgo;
	public String OnEstrogenReplacement;
	public String OnEstrogenReplacementMonths;
	public String OnEstrogenReplacementYears;
	public String BilateralOophorectomy;
	public String BilateralOophorectomyDate;
	public String Hysterectomy;
	public String HysterectomyDate;
	public String MenopausalStatus;
	public String CompletedDate;
	public String Status;	
}