public with sharing class OffStudyCRF {
  public String PatientId;
  public String Datepatientwentoffstudy;
  public String Patientcompletedstudyperprotocol;
  public String PatientdidnotwanttocompleteMRI;
  public String Patientdidntwanttocompletecorebio;
  public String Patientdidntcontinueontreatmentarm;
  public String Whypatientdidntcontinuetreatmentarm;
  public String Treatmentarmotherreason;
  public String Patientdidnothavesurgery;
  public String Patientdidnothavesurgeryreason;
  public String PatientDied;
  public String Didpatientwithdrawforsurvival;
  public String Patientwithdrewforspecimens;
  public String CompletedDate;
  public String Status;
  }