public with sharing class OnStudyEligibilityCRF {
	public String PatientId;
	public String NoClinicalOrImagingEvidence;
	public String NoUncontrolledorCardiovascularDiseas;
	public String NoHistoryOfAllergicReactions;
	public String NoUncontrolledIntercurrentIllness;
	public String NotHadASentinelLymphNode;
	public String LabValues;
	public String Leukocytes3000L;
	public String AbsoluteNeutrophilCount1500L;
	public String Platelets100000L;
	public String TotalBilirubinWithinInstitutional;
	public String ASTSGOTOrALTSGPT15xinsti;
	public String Creatinine15xInstitutionalULN;
	public String HowWasTheCancerFirstDetected;
	public String IsMassPalpable;
	public String OtherReasonForCancerFirstDetected;
	public String MassIdentificationDate;
	public String ScreeningMemogramPriorToMassDetect;
	public String MostRecentDate;
	public String CompletedDate;
	public String Status;
}