public with sharing class Patient {
	public String TestHarnessId;
	public String FirstName;
	public String MiddleName;
	public String LastName;
	public String Suffix;
	public String Gender;
	public String Birthdate;
	public String AddressLine1;
	public String AddressLine2;
	public String City;
	public String State;
	public String Country;
	public String Zip;
	public String Race;
	public String Ethnicity;
	public String MedicalRecordNumber;
	public String CountryOfBirth;
	public String completedDate;
	public String Status;
	
}