public with sharing class PreEligibilityCRF {
	public String PatientId;
	public String HistologicallyConfirmedInvasiveCancer;
	public String ClinicallyRadiologicallyMeasurable;
	public String CytotoxicRegiments;
	public String X30DaysInvestigationalAgents;
	public String NotHadPriorRT;
	public String PatientIs18yearsOrOlder;
	public String NonPregnantNotLactating;	
	public String NoFerromegnaticProstheses;
	public String WillingToHaveCoreBiospy;
	public String WillinToHaveStudyMRI;
	public String ECOGScore;
	public String PatientSignedUpISPY2Screening;	
	public String ReasonNotSigningScreeningConsent;
	public String CompletedDate;
	public String Status;
}