public with sharing class Procedure_OSP_PSS {
	public String CRFId;
	public String DateOfProcedure;
	public String ProcedureName;
	public String Ultrasound;
	public String Palpationguided;
	public String Mammography;
	public String MRI;
	public String Stereotactic;
	public String Laterality;
	public String Location;
	public String NodeResult;
	public String FormName;
	public String NodeType;
	public String TotalPositive;
	public String TotalExaminedNodes;
}