public with sharing class Procedure_Specimen_Detail_OSP_PSS {
  public String CRFId;
  public String Procedure;
  public String Specimen;
  public String MainSpecimensubmittedforhistology;
  public String SingleSpecimentsubmittedforhistology;
  public String MediallateralGrossspecimensize;
  public String Mediallateralsizeunit;
  public String AnteriordeepGrossspecimensize;
  public String Anteriordeepsizeunit;
  public String SuperorinferiorGrossspecimensize;
  public String Superorinferiorsizeunit;
  public String TotalSlices;
  public String SlicingMethod;
  public String SlicePlane1;
  public String Slice1;
  public String Block1;
  public String SlicePlane2;
  public String Slice2;
  public String Block2;
  public String PerformingLab;
  public String Lymphnodetissuepresentinsample;
 }