public with sharing class ProtocolViolationCRF {
  public String PatientId;
  public String DateOfProtocolViolation;
  public String Medicationnoncompliance;
  public String Visitnoncomplicance;
  public String Onstudyprocedurerequiredbyprotocol;
  public String Incorrecttherapygiventopatient;
  public String Screeningandonstudytestlabdone;
  public String Screeningprocedurerequired;
  public String Eligibilitycriteriaexception;
  public String Enrollmentofineligeligibleiblepatient;
  public String Patientbecamepregnantpriortosurgery;
  public String OtherViolationCheckbox;
  public String OtherTypeofViolation;
  public String Narrativedescription;
  public String PatientRemainsonStudy;
  public String Patientwithdrawn;
  public String OtherActionCheckbox;
  public String OtherActionTaken;
  public String LocalIRBNotified;
  public String CompletedDate;
  public String Status;
}