public with sharing class Staging_OSP_CRF {
  public String CRFId;
  public String Letarality;
  public String StagingModifierType;
  public String Modifiermultipleprimary;
  public String Modifierclassificationdone;
  public String Modifierindicatesrecurrent;
  public String Modifierdesignates;
  public String TumorType;
  public String NodeType;
  public String Metastasis;
  public String CalculatedStage;
  public String CalculatedStageValue;
  public String AdjudicatedStage;
  public String AdjudicatedBy;
  public String T4Tumorfinalstatus;  
}