public with sharing class TissueSpecimenCRF {
	public String PatientId;
	public String CRFId;
	public String ProcedureDate;
	public String GuidanceMethod;
	public String OtherGuidanceMethod;
	public String TimePoint;
	public String NumberOfCoreBiopsyCollected;
	public String ReasonAllSampleNotCollected;
	public String Other;
	public String PatientConsentedForThisStudy;
	public String PatientConsentedForOutSideStudy;
	public String CompletedDate;
	public String Status;
}