public with sharing class Toxicity_OSP_CRF {
  
  public String CRFId;
  public String SymptomStatus;
  public String SymptomMasters;
  public String ToxicityAgent;
  public String ToxicityOther;
  public String ToxicityStatus;
  public String Grade;
  public String Attribution;
  public String Waseventlifethreatning;
  public String Dideventrequiredhospitalization;
  public String Resultpersistentsignificantdisability;
  public String Resultconginentalabnormalitydefect;
  public String Didtheinvestigatorfindeventunusual;
  public String Dideventresultindeath;
  public String OnsetDate;
  public String SAE;
  public String Resolved;
  public String AEEndDate;
  public String PatientComplaint;
 }